name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        # Test the oldest and newest configuration on Mac and Windows
        - os: macos-latest
          python-version: 3.6
          toxenv: py36
        - os: macos-latest
          python-version: 3.8
          toxenv: py38
        # Test all configurations on Linux
        - os: ubuntu-latest
          python-version: 3.6
          toxenv: py36
        - os: ubuntu-latest
          python-version: 3.7
          toxenv: py37
        - os: ubuntu-latest
          python-version: 3.8
          toxenv: py38
        # Test multiple versions of the database
        - os: ubuntu-latest
          python-version: 3.8
          toxenv: py38 -- --ascii-dbase-root=https://www.chiantidatabase.org/download/CHIANTI_7.1.4_data.tar.gz --disable-file-hash
        - os: ubuntu-latest
          python-version: 3.8
          toxenv: py38 -- --ascii-dbase-root=https://www.chiantidatabase.org/download/CHIANTI_8.0.7_data.tar.gz
        - os: ubuntu-latest
          python-version: 3.8
          toxenv: py38 -- --ascii-dbase-root=https://www.chiantidatabase.org/download/CHIANTI_9.0.1_data.tar.gz --disable-file-hash
        # Docs
        - os: ubuntu-latest
          python-version: 3.8
          toxenv: build_docs
        # Code style checks
        - os: ubuntu-latest
          python-version: 3.8
          toxenv: codestyle

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade tox codecov
    - name: Run tox
      run: python -m tox -e  ${{ matrix.toxenv }}
    - name: Report coverage
      run: codecov
